[versions]
app-versionCode = "68"
app-versionName = "5.0.3"
ankiAndroid = "api-v1.1.0"
appcompat = "1.8.0"
camerak = "1.2"
constraintlayout = "2.2.2"
core = "1.7.0"
coreKtx = "1.19.1"
datastorePreferences = "1.2.1"
filekitCore = "0.16.0"
firebaseBom = "34.19.0"
googleApiServicesDrive = "v3-rev20250829-2.0.0"
jiebaAnalysis = "1.0.3"
junit = "1.3.0"
kotlin = "2.4.20"
ksp = "2.3.12"
compose = "1.12.1"
material3 = "1.9.0"
kotlinxDatetime = "0.8.0-0.6.x-compat"
kotlinxSerializationJson = "1.11.0"
kotlinxSerialization = "2.4.10"
material = "1.14.0"
navigationCompose = "2.9.2"
normalize = "1.4.0"
playServicesAuth = "22.0.0"
room = "3.0.3"
sqlite = "2.7.1"
kermit = "2.2.0"
compose_ui = "1.12.1"
textRecognitionChinese = "16.0.1"
ui = "1.12.1"
androidx-viewmodel = "2.11.0"
billingKtx = "9.1.0"
reviewKtx = "2.0.2"
workRuntimeKtxVersion = "2.12.0"
documentfile = "1.1.0"
androidGradlePlugin = "9.3.3"
googleServices = "4.5.0"
crashlytics = "3.0.8"
navigation = "2.10.2"
composePlugin = "1.12.1"
buildKonfig = "0.22.0"
turbine = "1.2.1"
kotlinxCoroutinesTest = "1.11.0"
activityCompose = "1.13.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastorePreferences" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-viewmodel" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-viewmodel" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-viewmodel" }
androidx-runner = { module = "androidx.test:runner", version.ref = "core" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtxVersion" }
anki-android = { module = "com.github.ankidroid:Anki-Android", version.ref = "ankiAndroid" }
camerak = { module = "io.github.kashif-mehmood-km:camerak", version.ref = "camerak" }
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekitCore" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekitCore" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekitCore" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
google-api-services-drive = { module = "com.google.apis:google-api-services-drive", version.ref = "googleApiServicesDrive" }
jieba-analysis = { module = "io.github.yrjyrj123:jieba-analysis", version.ref = "jiebaAnalysis" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose_ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose_ui" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material = { module = "com.google.android.material:material", version.ref = "material" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
normalize = { module = "com.doist.x:normalize", version.ref = "normalize" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
room-runtime = { module = "androidx.room3:room3-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room3:room3-compiler", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
androidx-room-sqlite-wrapper = { module = "androidx.room3:room3-sqlite-wrapper", version.ref = "room" }
text-recognition-chinese = { module = "com.google.mlkit:text-recognition-chinese", version.ref = "textRecognitionChinese" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "ui" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-viewmodel" }
androidx-lifecycle-viewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-viewmodel" }
androidx-lifecycle-runtimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-viewmodel" }
billing-ktx = { group = "com.android.billingclient", name = "billing-ktx", version.ref = "billingKtx" }
review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "reviewKtx" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidLint = { id = "com.android.lint", version.ref = "androidGradlePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composePlugin = { id = "org.jetbrains.compose", version.ref = "composePlugin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
navigation = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
room = { id = "androidx.room3", version.ref = "room" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinxSerialization" }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
androidKMP = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }